v1=int(input())
v2=int(input())
print("addition of ",v1,"+",v2,"is",v1+v2)
print("multiplication of ",v1,"*",v2,"is",v1*v2)
print("subraction of ",v1,"-",v2,"is",v1-v2)
print("division of ",v1,"/",v2,"is",v1/v2)
print("percentage of ",v1,"%",v2,"is",v1%v2)
print("floordiv of ",v1,"//",v2,"is",v1//v2)
print("Exponent of ",v1,"**",v2,"is",v1**v2)
